// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EncryptionRepository is an autogenerated mock type for the EncryptionRepository type
type EncryptionRepository struct {
	mock.Mock
}

type mockConstructorTestingTNewEncryptionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewEncryptionRepository creates a new instance of EncryptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEncryptionRepository(t mockConstructorTestingTNewEncryptionRepository) *EncryptionRepository {
	mock := &EncryptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
