// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MiddlewareRepository is an autogenerated mock type for the MiddlewareRepository type
type MiddlewareRepository struct {
	mock.Mock
}

type mockConstructorTestingTNewMiddlewareRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMiddlewareRepository creates a new instance of MiddlewareRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMiddlewareRepository(t mockConstructorTestingTNewMiddlewareRepository) *MiddlewareRepository {
	mock := &MiddlewareRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
